### PR TITLE
created dev branch for pull request

### PR DESCRIPTION
**Pull request by MaxJoles**
Hey @devonkoch hopefully I've set up this pull request properly and provided enough info to be helpful, If I haven't let me know what I can do to improve. Thanks!

[Webflow staging link](https://mp-sandbox.webflow.io/dash-2)

[Webflow Read Only](https://preview.webflow.com/preview/mp-sandbox?utm_medium=preview_link&utm_source=designer&utm_content=mp-sandbox&preview=a7e660ca19a0b7fffd43096e16362b48&pageId=5ef1237a0d51ce3c1ff232b8&mode=preview)

[Loom Explainer](https://www.loom.com/share/338668cf12d8467e9dff5a235588cb9c)

### CODE REVIEW

**Comment by devonkoch** [comment]
Hey Max,

Looks like you have your first pull request good, but I can only make comments on changed/modified lines, so the power of Github won't be possible for this pull request.

I watched your Loom, and re: figuring out the script loading issue: Memberstack's metadata object requires the `async/await` format, so removing that will break it.

JavaScript loads asynchronously, and removing the `async/await ` won't make it 'blocking', or synchronous. The DOM, however, loads synchronously, so the way I see it, from top to bottom, all of the Webflow HTML elements load, then the JS file from the finsweet cdn, then the `<script>` containing the custom finsweet code, and then the dashboard.js script.

Loading each of the 3 `<script>` tags are synchronous, but the execution of the code contained within is asynchronous. It's a bit much, I know lol.

So given what I know, there's a [race condition](https://wptheming.com/2011/01/javascript-race-conditions/#:~:text=A%20race%20condition%20is%20where,file%20had%20completely%20finished%20loading.) between the 2nd and 3rd `<script>` tags.

To solve this, there could be a way to load the 3rd `<script>` tag on the page after the 2nd `<script>` tag is finished executing, but the finsweet library doesn't provide a [promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) for when the  , Below is a code snippet that you can implement in your Webflow project to take care of this:

`
<script src="https://cdn.finsweet.com/files/cmslibrary-v1.4.js"></script>
<script>
(function() {
  var load1 = new FsLibrary('.hidden-list.cc-load-1')
  var load2 = new FsLibrary('.hidden-list.cc-load-2')

  load1.loadmore({
      button: ".cc-load-more", // class of Webflow Pagination button
      loadAll: true // loads ALL items in your pagination list after the page loads

  })

  load2.loadmore({
      button: ".cc-load-more", // class of Webflow Pagination button
      loadAll: true // loads ALL items in your pagination list after the page loads

  })


  // writes and executes the following script tag 2 seconds after reaching this code block
 // you can play with the timing to find a balance between code execution performance and page load speed
  setTimeout(() => {
    document.write('<script src = "https://maxjoles.github.io/makerpad/dashboard.js"></' + 'script>');
  }, 2000);

</script>
})();
`

**Comment by MaxJoles** [comment]
Thanks

**Comment by MaxJoles** [comment]
hahah oops, didn't mean to just respond with "thanks". 

But thanks for this. I was reading into the various rules and orders in which javascript processes on a page. Seems all over the place. The timeout should work perfectly in this instance, since the tabs obscure everything else, as you mentioned.

**Comment by MaxJoles** [comment]
@devonkoch Hmm this isn't working like I thought it would. I tried fixing it in several ways, but it keeps breaking the page. Here is a [video showing what's happening](https://www.loom.com/share/05dc6e3d686b474eb8ac0504315fa573)


And here is the code on the page. For some reason I can't get it to format as a code block in github

`<script src="https://cdn.finsweet.com/files/cmslibrary-v1.4.js"></script>
<script>
(function() {
  var load1 = new FsLibrary('.hidden-list.cc-load-1')
  var load2 = new FsLibrary('.hidden-list.cc-load-2')

  load1.loadmore({
      button: ".cc-load-more", // class of Webflow Pagination button
      loadAll: true // loads ALL items in your pagination list after the page loads

  })

  load2.loadmore({
      button: ".cc-load-more", // class of Webflow Pagination button
      loadAll: true // loads ALL items in your pagination list after the page loads

  })


  // writes and executes the following script tag 2 seconds after reaching this code block
 // you can play with the timing to find a balance between code execution performance and page load speed
  setTimeout(() => {
    document.write('<script src = "https://maxjoles.github.io/mp-dev/dashboard.js"></' + 'script>');
  }, 2000);
})();
</script>`

**Comment by MaxJoles** [comment]
It seems like the problem is likely with document.write [https://blog.dareboost.com/en/2016/09/avoid-using-document-write-scripts-injection/](https://blog.dareboost.com/en/2016/09/avoid-using-document-write-scripts-injection/)

**Comment by MaxJoles** [comment]
Ended up adapting the script using a slight different function, which is working now
`setTimeout(() => {
    var dashScript = document.createElement('script');
    dashScript.type = 'text/javascript';
    dashScript.src = 'https://maxjoles.github.io/mp-dev/dashboard.js';
    document.body.appendChild(dashScript);
    console.log('script added');
  }, 2000);`

But as mentioned in my text, now webflow pagination is broken.

**Comment by devonkoch** [comment]
Cool, glad you were able to snag that. Also, for large code blocks, add 3 tildas: "``` (code here) ```"

**Comment by MaxJoles** [comment]
Noted, I spent a while google searching how to do that with no luck

**Pull request closed without merging**
